### ISSUE TITLE
Why chrome-sidebar is not a dependency of github-trending?

### ISSUE THREAD

**Issue by yxliang01** [segmentio/chrome-sidebar#2]
I guess the reason why you didn't add it is because you have a globally linked `chrome-sidebar`? 
However, in this way, people who just want to try your github-trend example will not be able to just do `npm install`.

Thanks

**Comment by fouad** [comment]
oops! it should be (previously had it require `../../../dist` and forgot to run npm install again)

**Comment by yxliang01** [comment]
I would recommend you to have a separate repo for the example though. It's easier to try this thing I would say.

**Comment by fouad** [comment]
We're going for a structure similar to [zeit/next.js](https://github.com/zeit/next.js) since that seems to be easiest to work with for a lot of different types of examples.
